version: "3.9"

services:

  apoo-postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .postgres.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    command: postgres -c shared_buffers=512MB -c max_connections=400
    healthcheck:
      test: ["CMD", "pg_isready"]


networks:
  traefik:
    external: true