version: "3.9"

services:

  kub-postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: kub-postgres
    env_file:
      - .postgres.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    command: postgres -c shared_buffers=512MB -c max_connections=400
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
    networks:
      - traefik

  kub-postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    restart: unless-stopped
    container_name: kub-postgres-exporter
    env_file:
      - .postgres.env
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - kub-postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
    networks:
      - traefik


networks:
  traefik:
    external: true